from datetime import timedelta

ACCESS_TOKEN_TTL = timedelta(minutes=15)
REFRESH_TOKEN_TTL = timedelta(days=30)

JWT_ALGORITHM = "HS256"
JWT_SECRET = "change-me-in-production-32-bytes-minimum-key"

LOGIN_WINDOW_SECONDS = 3600
MAX_LOGIN_ATTEMPTS_PER_WINDOW = 10
LOCKOUT_SECONDS = 3600

INVITE_TTL_HOURS = 72
FREEMIUM_STUDENT_LIMIT_PER_TEACHER = 30

TOKEN_REUSE_ERROR = "TOKEN_REUSE_DETECTED"
